#!/usr/bin/env python3
"""Run AX's critical chat/workflow chains against a cached MLX model on a Mac.

The system prompt is generated by the Swift `ax-eval prompt <model-id>` command, so this
tests the shipping per-model profile instead of a hand-copied approximation. Set
HF_HUB_OFFLINE=1 when invoking it to guarantee the test never downloads or alters weights.
"""

import argparse
import hashlib
import importlib.metadata
import json
import os
import platform
import re
import time
from pathlib import Path


def tool_calls(text):
    payloads = re.findall(r"<tool_call>\s*(\{.*?\})\s*</tool_call>", text, re.S)
    if not payloads:
        stripped = text.strip()
        payloads = [stripped] if stripped.startswith("{") and stripped.endswith("}") else []
    calls = []
    for payload in payloads:
        try:
            value = json.loads(payload)
        except json.JSONDecodeError:
            continue
        if isinstance(value, dict) and isinstance(value.get("name"), str):
            calls.append(value)
    return calls


def normalized_cycle(raw):
    return [piece.strip().lower() for piece in re.split(r"[,;\n]", raw) if piece.strip()]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--model", default="mlx-community/Qwen3-1.7B-4bit")
    parser.add_argument("--prompt-file", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--seeds", default="1,2,3")
    parser.add_argument("--max-tokens", type=int, default=180)
    args = parser.parse_args()

    import mlx.core as mx
    from mlx_lm import load, stream_generate
    from mlx_lm.sample_utils import make_sampler

    system = args.prompt_file.read_text()
    prompt_sha256 = hashlib.sha256(system.encode()).hexdigest()
    hub_root = Path(os.environ.get("HF_HUB_CACHE", Path.home() / ".cache/huggingface/hub"))
    ref_path = hub_root / ("models--" + args.model.replace("/", "--")) / "refs/main"
    model_revision = ref_path.read_text().strip() if ref_path.exists() else None
    started = time.time()
    model, tokenizer = load(args.model)
    load_seconds = time.time() - started
    sampler = make_sampler(temp=0.2)

    def complete(messages, seed):
        mx.random.seed(seed)
        prompt = tokenizer.apply_chat_template(
            messages,
            add_generation_prompt=True,
            tokenize=False,
            enable_thinking=False,
        )
        return "".join(
            chunk.text
            for chunk in stream_generate(
                model, tokenizer, prompt, max_tokens=args.max_tokens, sampler=sampler
            )
        )

    def base(user):
        return [
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ]

    def response(content):
        return (
            "<tool_response>\n"
            + json.dumps({"content": content, "success": True}, separators=(",", ":"))
            + "\n</tool_response>"
        )

    expected_cycle = [
        "toggle_flashlight:on",
        "wait:0.25",
        "toggle_flashlight:off",
        "wait:0.25",
    ]
    runs = []
    all_passed = True
    for seed in [int(value) for value in args.seeds.split(",") if value]:
        checks = []

        for identifier, user in [
            ("greeting", "Hi"),
            ("joke", "Tell me a joke about penguins"),
            ("phone-fact", "How does a phone work?"),
        ]:
            completion = complete(base(user), seed)
            passed = bool(completion.strip()) and not tool_calls(completion)
            checks.append({"id": identifier, "passed": passed, "completions": [completion]})

        user = "Turn the flashlight on and off 5 times"
        completion = complete(base(user), seed)
        calls = tool_calls(completion)
        call = calls[0] if len(calls) == 1 else {}
        arguments = call.get("arguments", {})
        passed = (
            call.get("name") == "repeat_steps"
            and normalized_cycle(str(arguments.get("steps", ""))) in [
                expected_cycle,
                ["toggle_flashlight:on", "toggle_flashlight:off"],
                ["toggle_flashlight:on", "toggle_flashlight:off", "wait:0.25"],
            ]
            and int(arguments.get("times", 0)) == 5
        )
        checks.append({"id": "blink-five", "passed": passed, "completions": [completion]})

        user = "Toggle the light on and off then pause. Do this 10 times and then call 6316452763"
        messages = base(user)
        first = complete(messages, seed)
        first_calls = tool_calls(first)
        first_call = first_calls[0] if len(first_calls) == 1 else {}
        first_args = first_call.get("arguments", {})
        first_ok = (
            first_call.get("name") == "repeat_steps"
            and normalized_cycle(str(first_args.get("steps", ""))) == expected_cycle
            and int(first_args.get("times", 0)) == 10
        )
        if len(first_calls) >= 2:
            second = ""
            second_call = first_calls[1]
        else:
            messages.extend([
                {"role": "assistant", "content": first},
                {"role": "tool", "content": response(
                    "Ran the repeated flashlight sequence successfully. Continue with every "
                    "remaining action in the original request; do not give a final answer "
                    "until all requested actions have a tool result."
                )},
            ])
            second = complete(messages, seed)
            second_calls = tool_calls(second)
            second_call = second_calls[0] if len(second_calls) == 1 else {}
        digits = "".join(character for character in str(
            second_call.get("arguments", {}).get("number", "")
        ) if character.isdigit())
        checks.append({
            "id": "blink-ten-then-call",
            "passed": first_ok and second_call.get("name") == "call_number" and digits.endswith("6316452763"),
            "completions": [value for value in [first, second] if value],
        })

        user = "Turn on the flashlight, then pause the music, then set a timer for 2 minutes"
        completion = complete(base(user), seed)
        calls = tool_calls(completion)
        call = calls[0] if len(calls) == 1 else {}
        arguments = call.get("arguments", {})
        checks.append({
            "id": "x-then-y-then-z",
            "passed": (
                call.get("name") == "repeat_steps"
                and normalized_cycle(str(arguments.get("steps", ""))) == [
                    "toggle_flashlight:on", "play_music:pause", "set_timer:2"
                ]
                and int(arguments.get("times", 1)) == 1
            ),
            "completions": [completion],
        })

        seed_passed = all(check["passed"] for check in checks)
        all_passed = all_passed and seed_passed
        runs.append({"seed": seed, "passed": seed_passed, "checks": checks})

    report = {
        "model": args.model,
        "modelRevision": model_revision,
        "mlxLMVersion": importlib.metadata.version("mlx-lm"),
        "platform": platform.platform(),
        "promptFile": str(args.prompt_file),
        "promptSHA256": prompt_sha256,
        "loadSeconds": round(load_seconds, 3),
        "passed": all_passed,
        "runs": runs,
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(report, indent=2) + "\n")
    passed_count = sum(check["passed"] for run in runs for check in run["checks"])
    total = sum(len(run["checks"]) for run in runs)
    print(f"{passed_count}/{total} checks passed; report: {args.output}")
    if not all_passed:
        for run in runs:
            for check in run["checks"]:
                if not check["passed"]:
                    print(f"seed {run['seed']} FAIL {check['id']}")
        raise SystemExit(1)


if __name__ == "__main__":
    main()
